-- Inventário colaborativo com reversão total, RLS e exclusão permanente controlada.
-- Execute no SQL editor do Supabase ou via `supabase db push`.

begin;

create extension if not exists pgcrypto;

create table if not exists public.items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  patrimony_code text unique,
  acquisition_date date,
  acquisition_value numeric(14,2) check (acquisition_value is null or acquisition_value >= 0),
  current_state text,
  location text,
  responsible text,
  depreciation_rate numeric(6,3) default 0 check (depreciation_rate is null or depreciation_rate >= 0),
  is_deleted boolean not null default false,
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint items_deleted_consistency check (
    (is_deleted = false and deleted_at is null and deleted_by is null)
    or
    (is_deleted = true and deleted_at is not null)
  )
);

create table if not exists public.items_history (
  id bigint generated by default as identity primary key,
  uuid uuid not null default gen_random_uuid() unique,
  item_id uuid not null references public.items(id) on delete cascade,
  snapshot jsonb not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now(),
  change_summary text
);

create table if not exists public.files (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.items(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text,
  size bigint not null check (size >= 0),
  is_deleted boolean not null default false,
  uploaded_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

-- Configuração protegida. Defina o PIN com public.set_permanent_delete_pin('1234') usando service_role.
create table if not exists private_app_config (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

comment on table public.private_app_config is
  'Configuração interna sem acesso direto ao cliente. Use service_role para definir permanent_delete_pin_hash.';

-- O nome permanece em public para simplificar deploy no Supabase, mas sem privilégios/políticas de acesso direto.
alter table public.private_app_config enable row level security;

create index if not exists items_active_idx on public.items (is_deleted, updated_at desc);
create index if not exists items_history_item_changed_idx on public.items_history (item_id, changed_at desc, id desc);
create index if not exists files_item_idx on public.files (item_id, is_deleted);

create or replace function public.current_user_email()
returns text
language sql
stable
security definer
set search_path = auth, public
as $$
  select email from auth.users where id = auth.uid();
$$;

create or replace function public.item_change_summary(old_row public.items, new_row public.items)
returns text
language plpgsql
immutable
as $$
begin
  if old_row.is_deleted = false and new_row.is_deleted = true then
    return 'Item enviado para a lixeira';
  elsif old_row.is_deleted = true and new_row.is_deleted = false then
    return 'Item restaurado da lixeira';
  elsif old_row.acquisition_value is distinct from new_row.acquisition_value then
    return 'Valor de aquisição alterado';
  elsif old_row.location is distinct from new_row.location then
    return 'Localização alterada';
  elsif old_row.responsible is distinct from new_row.responsible then
    return 'Responsável alterado';
  else
    return 'Item atualizado';
  end if;
end;
$$;

create or replace function public.capture_item_history_before_update()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  insert into public.items_history (item_id, snapshot, changed_by, changed_at, change_summary)
  values (
    old.id,
    to_jsonb(old),
    auth.uid(),
    now(),
    public.item_change_summary(old, new)
  );

  new.updated_at := now();

  if new.is_deleted = true and old.is_deleted = false then
    new.deleted_at := coalesce(new.deleted_at, now());
    new.deleted_by := coalesce(new.deleted_by, auth.uid());
  elsif new.is_deleted = false then
    new.deleted_at := null;
    new.deleted_by := null;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_items_capture_history_before_update on public.items;
create trigger trg_items_capture_history_before_update
before update on public.items
for each row
when (old is distinct from new)
execute function public.capture_item_history_before_update();

create or replace function public.set_permanent_delete_pin(pin text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if pin !~ '^[0-9]{4}$' then
    raise exception 'A senha mestra deve conter exatamente 4 dígitos.' using errcode = '22023';
  end if;

  insert into public.private_app_config (key, value, updated_at)
  values ('permanent_delete_pin_hash', crypt(pin, gen_salt('bf')), now())
  on conflict (key) do update set value = excluded.value, updated_at = now();
end;
$$;

create or replace function public.permanently_delete_item(target_item_id uuid, master_pin text)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  configured_hash text;
begin
  if auth.uid() is null then
    raise exception 'Usuário autenticado obrigatório.' using errcode = '28000';
  end if;

  if master_pin !~ '^[0-9]{4}$' then
    raise exception 'Senha mestra inválida.' using errcode = '22023';
  end if;

  select value into configured_hash
  from public.private_app_config
  where key = 'permanent_delete_pin_hash';

  -- Alternativa para ambientes self-hosted: ALTER DATABASE ... SET app.permanent_delete_pin_hash = '<hash>';
  configured_hash := coalesce(configured_hash, nullif(current_setting('app.permanent_delete_pin_hash', true), ''));

  if configured_hash is null or crypt(master_pin, configured_hash) <> configured_hash then
    raise exception 'Senha mestra inválida.' using errcode = '28000';
  end if;

  if not exists (select 1 from public.items where id = target_item_id and is_deleted = true) then
    raise exception 'Item não encontrado na lixeira.' using errcode = 'P0002';
  end if;

  delete from public.files where item_id = target_item_id;
  delete from public.items_history where item_id = target_item_id;
  delete from public.items where id = target_item_id;
end;
$$;

create or replace function public.restore_item_version(target_history_uuid uuid)
returns public.items
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  h public.items_history%rowtype;
  restored public.items;
begin
  if auth.uid() is null then
    raise exception 'Usuário autenticado obrigatório.' using errcode = '28000';
  end if;

  select * into h from public.items_history where uuid = target_history_uuid;
  if not found then
    raise exception 'Versão histórica não encontrada.' using errcode = 'P0002';
  end if;

  update public.items
  set
    name = h.snapshot->>'name',
    description = h.snapshot->>'description',
    patrimony_code = h.snapshot->>'patrimony_code',
    acquisition_date = nullif(h.snapshot->>'acquisition_date', '')::date,
    acquisition_value = nullif(h.snapshot->>'acquisition_value', '')::numeric,
    current_state = h.snapshot->>'current_state',
    location = h.snapshot->>'location',
    responsible = h.snapshot->>'responsible',
    depreciation_rate = nullif(h.snapshot->>'depreciation_rate', '')::numeric,
    is_deleted = coalesce((h.snapshot->>'is_deleted')::boolean, false),
    deleted_at = (h.snapshot->>'deleted_at')::timestamptz,
    deleted_by = nullif(h.snapshot->>'deleted_by', '')::uuid
  where id = h.item_id
  returning * into restored;

  if not found then
    raise exception 'Item original não existe mais.' using errcode = 'P0002';
  end if;

  return restored;
end;
$$;

create or replace view public.items_with_last_change as
select
  i.*,
  u.email as last_changed_by_email,
  h.changed_at as last_changed_at,
  h.change_summary as last_change_summary
from public.items i
left join lateral (
  select changed_by, changed_at, change_summary
  from public.items_history ih
  where ih.item_id = i.id
  order by ih.changed_at desc, ih.id desc
  limit 1
) h on true
left join auth.users u on u.id = h.changed_by;

alter table public.items enable row level security;
alter table public.items_history enable row level security;
alter table public.files enable row level security;

-- Permissões SQL: clientes autenticados podem CRUD em items/files; histórico só SELECT/INSERT.
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.items to authenticated;
grant select, insert, update, delete on public.files to authenticated;
grant select, insert on public.items_history to authenticated;
grant usage, select on sequence public.items_history_id_seq to authenticated;
grant select on public.items_with_last_change to authenticated;
revoke all on function public.set_permanent_delete_pin(text) from public;
revoke all on function public.permanently_delete_item(uuid, text) from public;
revoke all on function public.restore_item_version(uuid) from public;
grant execute on function public.set_permanent_delete_pin(text) to service_role;
grant execute on function public.permanently_delete_item(uuid, text) to authenticated;
grant execute on function public.restore_item_version(uuid) to authenticated;
revoke all on public.private_app_config from anon, authenticated;
revoke update, delete on public.items_history from anon, authenticated;

create policy "items_authenticated_select" on public.items
  for select to authenticated using (true);
create policy "items_authenticated_insert" on public.items
  for insert to authenticated with check (true);
create policy "items_authenticated_update" on public.items
  for update to authenticated using (true) with check (true);
create policy "items_authenticated_delete" on public.items
  for delete to authenticated using (true);

create policy "files_authenticated_select" on public.files
  for select to authenticated using (true);
create policy "files_authenticated_insert" on public.files
  for insert to authenticated with check (true);
create policy "files_authenticated_update" on public.files
  for update to authenticated using (true) with check (true);
create policy "files_authenticated_delete" on public.files
  for delete to authenticated using (true);

create policy "history_authenticated_select" on public.items_history
  for select to authenticated using (true);
create policy "history_authenticated_insert" on public.items_history
  for insert to authenticated with check (true);

commit;
